### ISSUE TITLE
Hello, how to configure in lazyvim

### ISSUE THREAD

**Issue by ClzSkywalker** [RobertPietraru/bloc.nvim#1]
**I am a nvim novice, I so configuration error, not clear how to configure normal**

`    {
        'RobertPietraru/bloc.nvim',
        keys = { {
            "<leader>cbc",
            "<cmd>require('bloc').create_cubit('cubit_name', 'parent/folder/relative/path')<cr>",
            -- function ()
            --     require('bloc').create_cubit('cubit_name', 'parent/folder/relative/path')
            -- end,
            desc = "bloc cubit"
        }, {
            "<leader>cbb",
            "<cmd>require('bloc').create_bloc('bloc_name', 'parent/folder/relative/path')<cr>",
            -- function ()
            --     require('bloc').create_bloc('bloc_name', 'parent/folder/relative/path')
            -- end,
            desc = "bloc bloc"
        } },
    }`

**Comment by RobertPietraru** [comment]
Hello, if you go through the entire README you'll see my configuration. Personally, I don't use lazyvim so I cannot help you with that unfortunately. 

My plugin only does the snippets and the code generation. You have to find a way to get the path you want and the name of the bloc your own way. 

Here's some suggestions though. Find a way to get the selected folder in the file navigator you have and then a way to read text input. Afterwards just use the functions I've provided and you're good to go.

**Comment by ClzSkywalker** [comment]
Thanks for your reminding, I spent some time to learn neo-tree api, and it has been compatible with lazyvim. But it still had problems with line breaks, and I submitted a fork

```lua
    {
        'ClzSkywalker/bloc.nvim',
        keys = { {
            "<leader>cb",
            desc = "flutter bloc"
        }, {
            "<leader>cbc",
            function()
                local state = require("neo-tree.sources.manager").get_state("filesystem")
                local node = state.tree:get_node()
                local inputstr = vim.fn.input("Cubit Name:", "")
                require('bloc').create_cubit(inputstr, node.path .. '/')
            end,
            desc = "bloc cubit"
        }, {
            "<leader>cbb",
            function()
                local state = require("neo-tree.sources.manager").get_state("filesystem")
                local node = state.tree:get_node()
                local inputstr = vim.fn.input("Bloc Name:", "")
                require('bloc').create_bloc(inputstr, node.path .. '/')
            end,
            desc = "bloc bloc"
        } },
    }
```
